/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-03-13 18:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.blog.entity.*;

public final class adminportal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 User user = null; 
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.blog.entity");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- basic -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- mobile metas -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\r\n");
      out.write("    <!-- site metas -->\r\n");
      out.write("    <title>Dashboard</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"/images/favicon.png\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <!-- bootstrap css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <!-- style css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("    <!-- Responsive-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("    <!-- fevicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\r\n");
      out.write("    <!-- Scrollbar Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("    <!-- Tweaks for older IEs-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\r\n");
      out.write("    <!-- owl stylesheets -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesoeet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css\"\r\n");
      out.write("        media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/tailwind.output.css\" />\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js\" defer></script>\r\n");
      out.write("    <script src=\"./assets/js/charts-lines.js\" defer></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 user = (User)request.getSession().getAttribute("user"); 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <!-- header section start -->\r\n");
      out.write("    <div class=\"header_section\">\r\n");
      out.write("        <div class=\"container-fluid header_main\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("                <a class=\"logo\" href=\"index.jsp\"><img src=\"images/logo.png\"></a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("                    aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"blog.jsp\">Blog</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown2\" role=\"button\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
      out.print( "Hi "+user.getUserName() );
      out.write("</a>\r\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown2\">\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"dashboard.jsp\">Profile</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"notification.jsp\">Notifications</a>\r\n");
      out.write("                                ");
      out.print( user.getRole() == "admin" ? "<a class=\"dropdown-item\" href=\"adminportal.jsp\">Admin Protal</a>" : "");
      out.write("\r\n");
      out.write("                                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                <<form method=\"post\" action=\"LogOutServlet\"><input type=\"submit\" class=\"dropdown-item\" value=\"LogOut\"><form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- header section end -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container px-6 mx-auto grid\">\r\n");
      out.write("        <h2 class=\"my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200\">\r\n");
      out.write("            Dashboard\r\n");
      out.write("        </h2>\r\n");
      out.write("        <!-- CTA -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Cards -->\r\n");
      out.write("        <div class=\"grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4\">\r\n");
      out.write("            <!-- Card -->\r\n");
      out.write("            <div class=\"flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800\">\r\n");
      out.write("                <div\r\n");
      out.write("                    class=\"p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500\">\r\n");
      out.write("                    <svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 25 25\">\r\n");
      out.write("                    <path xmlns=\"http://www.w3.org/2000/svg\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("                        d=\"M6.50959 2C4.01895 2 1.99988 4.01907 1.99988 6.50971V17.4903C1.99988 19.9809 4.01895 22 6.50959 22H11.8499C12.3191 22 12.6994 21.6197 12.6994 21.1505C12.6994 20.6813 12.3191 20.301 11.8499 20.301H6.50959C4.9573 20.301 3.69892 19.0426 3.69892 17.4903V6.50971C3.69892 4.95742 4.9573 3.69904 6.50959 3.69904H17.1902C18.7425 3.69904 20.0008 4.95742 20.0008 6.50971V12C20.0008 12.4692 20.3812 12.8495 20.8504 12.8495C21.3195 12.8495 21.6999 12.4692 21.6999 12V6.50971C21.6999 4.01907 19.6808 2 17.1902 2H6.50959ZM7.00245 11.1503C6.53327 11.1503 6.15293 11.5306 6.15293 11.9998C6.15293 12.469 6.53327 12.8493 7.00245 12.8493H10.0016C10.4708 12.8493 10.8511 12.469 10.8511 11.9998C10.8511 11.5306 10.4708 11.1503 10.0016 11.1503H7.00245ZM6.15293 8.00201C6.15293 7.53283 6.53327 7.15248 7.00245 7.15248H12.9991C13.4683 7.15248 13.8486 7.53283 13.8486 8.00201C13.8486 8.47119 13.4683 8.85153 12.9991 8.85153H7.00245C6.53327 8.85153 6.15293 8.47119 6.15293 8.00201ZM19.4325 13.2912C18.9054 12.7553 18.0508 12.7553 17.5237 13.2912L13.7673 17.1101C13.4779 17.4044 13.3355 17.8162 13.38 18.2297L13.5949 20.2252C13.6508 20.7447 14.0542 21.1549 14.5652 21.2117L16.528 21.4301C16.9348 21.4754 17.3398 21.3306 17.6292 21.0364L21.3856 17.2174C21.9126 16.6815 21.9126 15.8127 21.3856 15.2768L19.4325 13.2912ZM15.0725 18.2059L18.4781 14.7435L19.9571 16.2471L16.5515 19.7095L15.2184 19.5612L15.0725 18.2059Z\"\r\n");
      out.write("                        fill=\"#1C1C1C\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mb-2 text-sm font-medium text-gray-600 dark:text-gray-400\">\r\n");
      out.write("                        Total Reports\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"text-lg font-semibold text-gray-700 dark:text-gray-200\">\r\n");
      out.write("                        30\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800\">\r\n");
      out.write("                <div\r\n");
      out.write("                    class=\"p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500\">\r\n");
      out.write("                    <svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 25 25\">\r\n");
      out.write("                    <path xmlns=\"http://www.w3.org/2000/svg\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("                        d=\"M6.50663 3.69435C4.95347 3.69435 3.69438 4.95344 3.69438 6.50661V17.4934C3.69438 19.0465 4.95347 20.3056 6.50664 20.3056H17.4934C19.0465 20.3056 20.3056 19.0465 20.3056 17.4933V12C20.3056 11.5305 20.6862 11.15 21.1556 11.15C21.6251 11.15 22.0056 11.5305 22.0056 12V17.4933C22.0056 19.9854 19.9854 22.0056 17.4934 22.0056H6.50664C4.01459 22.0056 1.99438 19.9854 1.99438 17.4934V6.50661C1.99438 4.01456 4.01459 1.99435 6.50663 1.99435H12C12.4694 1.99435 12.85 2.37491 12.85 2.84435C12.85 3.3138 12.4694 3.69435 12 3.69435H6.50663Z\"\r\n");
      out.write("                        fill=\"#1C1C1C\" />\r\n");
      out.write("                        <circle xmlns=\"http://www.w3.org/2000/svg\" cx=\"18.5\" cy=\"5.5\" r=\"2.65\" stroke=\"#1C1C1C\" stroke-width=\"1.7\" />\r\n");
      out.write("                        <path xmlns=\"http://www.w3.org/2000/svg\" d=\"M7 16H11.0406\" stroke=\"#1C1C1C\" stroke-width=\"1.7\" stroke-linecap=\"round\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mb-2 text-sm font-medium text-gray-600 dark:text-gray-400\">\r\n");
      out.write("                        Today Reports\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"text-lg font-semibold text-gray-700 dark:text-gray-200\">\r\n");
      out.write("                        5\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Card -->\r\n");
      out.write("            <div class=\"flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800\">\r\n");
      out.write("                <div class=\"p-3 mr-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500\">\r\n");
      out.write("                    <svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 23 23\">\r\n");
      out.write("                        <path xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                            d=\"M5.755,20.283,4,8H20L18.245,20.283A2,2,0,0,1,16.265,22H7.735A2,2,0,0,1,5.755,20.283ZM21,4H16V3a1,1,0,0,0-1-1H9A1,1,0,0,0,8,3V4H3A1,1,0,0,0,3,6H21a1,1,0,0,0,0-2Z\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mb-2 text-sm font-medium text-gray-600 dark:text-gray-400\">\r\n");
      out.write("                        Content Removed\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"text-lg font-semibold text-gray-700 dark:text-gray-200\">\r\n");
      out.write("                        5\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Card -->\r\n");
      out.write("            <div class=\"flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800\">\r\n");
      out.write("                <div class=\"p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500\">\r\n");
      out.write("                    <svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 -3 45 45\">\r\n");
      out.write("                        <path xmlns=\"http://www.w3.org/2000/svg\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("                            d=\"M40 36V14L30 4H16C13.7909 4 12 5.79086 12 8V36C12 38.2091 13.7909 40 16 40H36C38.2091 40 40 38.2091 40 36ZM36.1716 13L31 7.82843V13H36.1716ZM32.7071 22.7071C33.0976 22.3166 33.0976 21.6834 32.7071 21.2929C32.3166 20.9024 31.6834 20.9024 31.2929 21.2929L24 28.5858L20.7071 25.2929C20.3166 24.9024 19.6834 24.9024 19.2929 25.2929C18.9024 25.6834 18.9024 26.3166 19.2929 26.7071L24 31.4142L32.7071 22.7071Z\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mb-2 text-sm font-medium text-gray-600 dark:text-gray-400\">\r\n");
      out.write("                        Content Retained\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"text-lg font-semibold text-gray-700 dark:text-gray-200\">\r\n");
      out.write("                        376\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Card -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- New Table -->\r\n");
      out.write("        <div class=\" overflow-hidden rounded-lg shadow-xs\">\r\n");
      out.write("            <div class=\"w-full overflow-x-auto\">\r\n");
      out.write("                <table class=\"w-full whitespace-no-wrap\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr\r\n");
      out.write("                            class=\"text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800\">\r\n");
      out.write("                            <th class=\"px-4 py-3\">User Name</th>\r\n");
      out.write("                            <th class=\"px-4 py-3\">Content Owner</th>\r\n");
      out.write("                            <th class=\"px-4 py-3\">Status</th>\r\n");
      out.write("                            <th class=\"px-4 py-3\">Report Date</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody class=\"bg-white divide-y dark:divide-gray-700 dark:bg-gray-800\">\r\n");
      out.write("                        <tr class=\"text-gray-700 dark:text-gray-400\">\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-5.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo User</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-6.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo Creater</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-xs\">\r\n");
      out.write("                                <span\r\n");
      out.write("                                    class=\"px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100\">\r\n");
      out.write("                                    Removed\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-sm\">\r\n");
      out.write("                                6/10/2020\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("                        <tr class=\"text-gray-700 dark:text-gray-400\">\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-5.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo User</p>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-6.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo Creater</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-xs\">\r\n");
      out.write("                                <span\r\n");
      out.write("                                    class=\"px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100\">\r\n");
      out.write("                                    Retained\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-sm\">\r\n");
      out.write("                                6/10/2020\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"text-gray-700 dark:text-gray-400\">\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-5.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo User</p>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-6.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo Creater</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-xs\">\r\n");
      out.write("                                <span\r\n");
      out.write("                                    class=\"px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100\">\r\n");
      out.write("                                    Removed\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-sm\">\r\n");
      out.write("                                6/10/2020\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"text-gray-700 dark:text-gray-400\">\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-5.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo User</p>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-6.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo Creater</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-xs\">\r\n");
      out.write("                                <span\r\n");
      out.write("                                    class=\"px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100\">\r\n");
      out.write("                                    Removed\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-sm\">\r\n");
      out.write("                                6/10/2020\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"text-gray-700 dark:text-gray-400\">\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-5.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo User</p>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3\">\r\n");
      out.write("                                <div class=\"flex items-center text-sm\">\r\n");
      out.write("                                    <!-- Avatar with inset shadow -->\r\n");
      out.write("                                    <div class=\"relative hidden w-8 h-8 mr-3 rounded-full md:block\">\r\n");
      out.write("                                        <img class=\"object-cover w-full h-full rounded-full\" src=\"./images/img-6.png\"\r\n");
      out.write("                                            alt=\"\" loading=\"lazy\">\r\n");
      out.write("                                        <div class=\"absolute inset-0 rounded-full shadow-inner\" aria-hidden=\"true\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"font-semibold\">Demo Creater</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-xs\">\r\n");
      out.write("                                <span\r\n");
      out.write("                                    class=\"px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100\">\r\n");
      out.write("                                    Retained\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"px-4 py-3 text-sm\">\r\n");
      out.write("                                6/10/2020\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div\r\n");
      out.write("                class=\"grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800\">\r\n");
      out.write("                <span class=\"flex items-center col-span-3\">\r\n");
      out.write("                    Showing 21-30 of 100\r\n");
      out.write("                </span>\r\n");
      out.write("                <span class=\"col-span-2\"></span>\r\n");
      out.write("                <!-- Pagination -->\r\n");
      out.write("                <span class=\"flex col-span-4 mt-2 sm:mt-auto sm:justify-end\">\r\n");
      out.write("                    <nav aria-label=\"Table navigation\">\r\n");
      out.write("                        <ul class=\"inline-flex items-center\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button\r\n");
      out.write("                                    class=\"px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple\"\r\n");
      out.write("                                    aria-label=\"Previous\">\r\n");
      out.write("                                    <svg aria-hidden=\"true\" class=\"w-4 h-4 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("                                        <path\r\n");
      out.write("                                            d=\"M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z\"\r\n");
      out.write("                                            clip-rule=\"evenodd\" fill-rule=\"evenodd\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button class=\"px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    1\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button class=\"px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    2\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button\r\n");
      out.write("                                    class=\"px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    3\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button class=\"px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    4\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span class=\"px-3 py-1\">...</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button class=\"px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    8\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button class=\"px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple\">\r\n");
      out.write("                                    9\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <button\r\n");
      out.write("                                    class=\"px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple\"\r\n");
      out.write("                                    aria-label=\"Next\">\r\n");
      out.write("                                    <svg class=\"w-4 h-4 fill-current\" aria-hidden=\"true\" viewBox=\"0 0 20 20\">\r\n");
      out.write("                                        <path\r\n");
      out.write("                                            d=\"M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z\"\r\n");
      out.write("                                            clip-rule=\"evenodd\" fill-rule=\"evenodd\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800\">\r\n");
      out.write("                <div class=\"chartjs-size-monitor\">\r\n");
      out.write("                    <div class=\"chartjs-size-monitor-expand\">\r\n");
      out.write("                        <div class=\"\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chartjs-size-monitor-shrink\">\r\n");
      out.write("                        <div class=\"\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h4 class=\"mb-4 font-semibold text-gray-800 dark:text-gray-300\">\r\n");
      out.write("                    Number of Reports\r\n");
      out.write("                </h4>\r\n");
      out.write("                <canvas id=\"line\" style=\"display: block; width: 840px; height: 420px;\" width=\"840\" height=\"400\"\r\n");
      out.write("                    class=\"chartjs-render-monitor\"></canvas>\r\n");
      out.write("                <div class=\"flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400\">\r\n");
      out.write("                    <!-- Chart legend -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- footer section start -->\r\n");
      out.write("    <div class=\"footer_section layout_padding\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer_menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("                    <li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("                    <li><a href=\"contact.jsp\">Contact us</a></li>\r\n");
      out.write("                    <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer_menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"contact_menu\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"images/call-icon.png\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\">Call : +01 1234567890</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"contact_menu\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"blog.jsp\"><img src=\"images/mail-icon.png\"></a></li>\r\n");
      out.write("                                <li><a href=\"features.jsp\">demo@gmail.com</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- footer section end -->\r\n");
      out.write("    <!-- copyright section start -->\r\n");
      out.write("    <!-- <div class=\"copyright_section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p class=\"copyright_text\">Copyright 2020 All Right Reserved By.<a href=\"https://html.design\"> Free html\r\n");
      out.write("                    Templates</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("    <!-- copyright section end -->\r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script id=\"rendered-js\">\r\n");
      out.write("        const $dropdown = $(\".dropdown\");\r\n");
      out.write("        const $dropdownToggle = $(\".dropdown-toggle\");\r\n");
      out.write("        const $dropdownMenu = $(\".dropdown-menu\");\r\n");
      out.write("        const showClass = \"show\";\r\n");
      out.write("\r\n");
      out.write("        $(window).on(\"load resize\", function () {\r\n");
      out.write("            if (this.matchMedia(\"(min-width: 768px)\").matches) {\r\n");
      out.write("                $dropdown.hover(\r\n");
      out.write("                    function () {\r\n");
      out.write("                        const $this = $(this);\r\n");
      out.write("                        $this.addClass(showClass);\r\n");
      out.write("                        $this.find($dropdownToggle).attr(\"aria-expanded\", \"true\");\r\n");
      out.write("                        $this.find($dropdownMenu).addClass(showClass);\r\n");
      out.write("                    },\r\n");
      out.write("                    function () {\r\n");
      out.write("                        const $this = $(this);\r\n");
      out.write("                        $this.removeClass(showClass);\r\n");
      out.write("                        $this.find($dropdownToggle).attr(\"aria-expanded\", \"false\");\r\n");
      out.write("                        $this.find($dropdownMenu).removeClass(showClass);\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("                $dropdown.off(\"mouseenter mouseleave\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    //# sourceURL=pen.js\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-3.0.0.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugin.js\"></script>\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("    <!-- javascript -->\r\n");
      out.write("    <script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("    <script src=\"https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
